apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: auto-go0329
  janus-idp.io/tekton: auto-go0329
  backstage.io/kubernetes-id: auto-go0329
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: auto-go0329
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
